### ISSUE TITLE
Having a weird problem with this

### ISSUE THREAD

**Issue by AndreiSalamon** [yasirkula/Unity360ScreenshotCapture#3] opened 2018-07-04 10:52 UTC
When I create the panorama, it looks very weird, like it's a blend of 2 images on top of eachother :|
![test](https://user-images.githubusercontent.com/31312308/42273309-811ca490-7f91-11e8-977b-5421e25abb1c.jpg)

**Comment by AndreiSalamon** [comment] 2018-07-04 10:58
NVM, it was because of the post effects stack. I was using Vignette and TAA, neither of which can work with this method of 360 capture.

**Comment by AndreiSalamon** [comment] 2018-07-04 11:03
Although the SSAO is also causing issues.

**Comment by AndreiSalamon** [comment] 2018-07-04 11:06
AO issue:
![test](https://user-images.githubusercontent.com/31312308/42273926-6dfac124-7f93-11e8-8d37-2c40351edb76.jpg)

**Comment by AndreiSalamon** [comment] 2018-07-04 11:12
Only HBAO seems to work correctly.

**Comment by yasirkula** [comment] 2018-07-04 13:00
The ambient occlusion issue can also be seen here (in case you'd like to bump that issue): https://github.com/Unity-Technologies/PostProcessing/issues/331

If you are using Post-processing stack v1, you can [try using v2](https://github.com/Unity-Technologies/PostProcessing) to see if the issue(s) are fixed on that version.

**Comment by yasirkula** [comment] 2018-07-20 15:56
Closing this issue because it is not caused by the plugin itself.

**Closed as completed by yasirkula** 2018-07-20 15:56 UTC
