### ISSUE TITLE
Blurry Images

### ISSUE THREAD

**Issue by ghost** [yasirkula/Unity360ScreenshotCapture#9] opened 2020-04-16 16:07 UTC
Hello, thanks for the plugin. It's really useful!
I use Unity 2019.3.3f1 on Windows 10 in HDRP project. There are strange blurry footprints

![1](https://user-images.githubusercontent.com/61880851/79479356-4fd13280-8015-11ea-815a-8d373d768309.jpeg)

**Comment by ghost** [comment] 2020-04-16 16:27
On Flickr: https://flic.kr/p/2iR11mP

**Comment by yasirkula** [comment] 2020-04-16 19:12
Most probably caused by post-processing but I am not sure which effect to blame. You can try disabling motion blur or depth of field effects to see if the issue is resolved. If it is, then I'd recommend you to temporarily disable those effect before capturing the 360 screenshot and then reenable them.

P.S. Unity's Camera.RenderToCubemap function itself is affected by this issue, so this issue can't be resolved by modifying 360ScreenshotCapture.

**Comment by ghost** [comment] 2020-04-17 09:31
@yasirkula Disabling motion blur is resolve. But still there is footprints from cubemap. You gave me direction. Thank you for help!

**Closed as completed** 2020-04-17 11:15 UTC

**Comment by Levrden** [comment] 2020-06-18 03:49
Just spent all my day trying to resolve this... THANKS !!
Sometimes the default post processing in HDRP is just so annoying
